Get PDF + verapdf xml out even if verapdf fails

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -44,10 +44,14 @@ jobs:
           if [ "$ACT" = "true" ]; then
             echo "No docker in ACT"
           else
-            docker run --rm -t -v "$(pwd):/data" docker.io/verapdf/cli:v1.28.2 -f 1b main.pdf
+            set -o pipefail   # ensure Docker exit code is propagated
+            docker run --rm -t -v "$(pwd):/data" docker.io/verapdf/cli:v1.28.2 -f 1b --format xml main.pdf | tee verapdf.xml
           fi
       - name: Upload PDF
+        if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: pdf
-          path: main.pdf
+          name: pdf-and-verapdf
+          path: |
+	      main.pdf
+	      verapdf.xml
